// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

// Mirrors `serde_json::Value` on the wire. The auth pages flash validation
// errors through it as a field -> messages map.
export type Value = Record<string, string[]>;

// Mirrors `controllers::dashboard::UserInfo`.
export interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export interface RegisterProps {
  errors: Value | null;
}

export interface HomeProps {
  title: string;
  message: string;
}

export interface LoginProps {
  errors: Value | null;
}

export interface DashboardProps {
  user: UserInfo;
}

