// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

// Mirrors `controllers::dashboard::UserInfo`.
export interface UserInfo {
  id: number;
  name: string;
  email: string;
}

// The auth pages carry no per-page props: validation errors ride Inertia's
// own `errors` prop, which `useForm` merges into `form.errors`.
export interface RegisterProps {}

export interface HomeProps {
  title: string;
  message: string;
}

export interface LoginProps {}

export interface DashboardProps {
  user: UserInfo;
}
